language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-24.0.0
    - android-24

script: "./gradlew build --stacktrace"
